# -*- coding: utf-8 -*-
"""umarfarooq-Week1_Pandas_NumPy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wVWpgUIxIvegpB83zss5D1jfo6uBvW06

#  Week 1 — Intro to Pandas & NumPy
**Dataset:** World Population (234 countries, 1970–2022)

**Objective:** Load, inspect, and summarise a real-world CSV dataset using Pandas and NumPy.

**Skills covered:** Data Loading · Data Inspection · Basic Aggregation

**Tools:** `pandas` · `numpy` · `matplotlib`

---
## 1. Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:,.2f}'.format)

print('Libraries loaded successfully!')
print(f'Pandas version : {pd.__version__}')
print(f'NumPy  version : {np.__version__}')

"""---
## 2. Data Loading
> Load the CSV file into a Pandas DataFrame
"""

# Load dataset
df = pd.read_csv('/content/world_population.csv')

print(f'✅ Dataset loaded successfully!')
print(f'   Shape : {df.shape[0]} rows × {df.shape[1]} columns')

"""---
## 3. Data Inspection
> Explore the structure, types, and quality of the data
"""

# 3.1 First 5 rows
print('--- First 5 Rows ---')
df.head()

# 3.2 Last 5 rows
print('--- Last 5 Rows ---')
df.tail()

# 3.3 Column names and data types
print('--- Column Names & Data Types ---')
df.info()

# 3.4 Check for missing values
print('--- Missing Values per Column ---')
missing = df.isnull().sum()
print(missing)
print(f'\nTotal missing values: {missing.sum()}')

# 3.5 Unique continents
print('--- Unique Continents ---')
print(df['Continent'].unique())
print(f'Count: {df["Continent"].nunique()}')

# 3.6 Check for duplicates
duplicates = df.duplicated().sum()
print(f'Duplicate rows: {duplicates}')

"""---
## 4. Basic Statistics (Pandas + NumPy)
> Summarise the numerical columns
"""

# 4.1 Pandas .describe() — gives count, mean, std, min, quartiles, max
print('--- Statistical Summary ---')
df.describe()

# 4.2 NumPy array operations on 2022 Population
pop_2022 = df['2022 Population'].to_numpy()

print('=== NumPy Array Operations on 2022 Population ===')
print(f'  Total world population (2022) : {np.sum(pop_2022):>15,.0f}')
print(f'  Mean population               : {np.mean(pop_2022):>15,.0f}')
print(f'  Median population             : {np.median(pop_2022):>15,.0f}')
print(f'  Std deviation                 : {np.std(pop_2022):>15,.0f}')
print(f'  Min population                : {np.min(pop_2022):>15,.0f}')
print(f'  Max population                : {np.max(pop_2022):>15,.0f}')
print(f'  25th percentile               : {np.percentile(pop_2022, 25):>15,.0f}')
print(f'  75th percentile               : {np.percentile(pop_2022, 75):>15,.0f}')

# 4.3 Population growth: 2022 vs 1970
df['Growth_1970_2022'] = df['2022 Population'] - df['1970 Population']
df['Growth_%'] = ((df['2022 Population'] - df['1970 Population']) / df['1970 Population'] * 100).round(2)

print('Top 5 fastest growing countries (1970 → 2022):')
print(df[['Country/Territory','1970 Population','2022 Population','Growth_%']]
      .sort_values('Growth_%', ascending=False).head())

"""---
## 5. Basic Aggregation
> Group data by Continent and aggregate
"""

# 5.1 Population by Continent (2022)
continent_pop = df.groupby('Continent')['2022 Population'].agg(
    Countries='count',
    Total_Population='sum',
    Mean_Population='mean',
    Max_Population='max'
).sort_values('Total_Population', ascending=False)

print('--- 2022 Population by Continent ---')
continent_pop

# 5.2 Top 10 most populous countries in 2022
top10 = df.nlargest(10, '2022 Population')[['Country/Territory','Continent','2022 Population','World Population Percentage']]
print('--- Top 10 Most Populous Countries (2022) ---')
top10

# 5.3 Average population density by continent
density = df.groupby('Continent')['Density (per km²)'].mean().sort_values(ascending=False)
print('--- Average Population Density by Continent (per km²) ---')
print(density.round(2))

"""---
## 6. Pandas Series Operations
> Demonstrate Series creation and operations
"""

# 6.1 Extract a Series
pop_series = df.set_index('Country/Territory')['2022 Population']
print('--- Population Series (first 5) ---')
print(pop_series.head())
print(f'\nType: {type(pop_series)}')
print(f'dtype: {pop_series.dtype}')

# 6.2 Boolean filtering on Series
billion_plus = pop_series[pop_series > 1_000_000_000]
print('--- Countries with population > 1 Billion ---')
print(billion_plus)

"""---
## 7. Visualisations (matplotlib)
> Plot key insights from the dataset
"""

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle('World Population Analysis — 2022', fontsize=16, fontweight='bold', y=1.01)

# Plot 1 — Top 10 countries bar chart
ax1 = axes[0, 0]
top10_sorted = top10.sort_values('2022 Population')
ax1.barh(top10_sorted['Country/Territory'], top10_sorted['2022 Population'] / 1e9, color='steelblue')
ax1.set_xlabel('Population (Billions)')
ax1.set_title('Top 10 Most Populous Countries (2022)')
ax1.grid(axis='x', alpha=0.3)

# Plot 2 — Population by continent (pie)
ax2 = axes[0, 1]
cont_totals = df.groupby('Continent')['2022 Population'].sum()
ax2.pie(cont_totals, labels=cont_totals.index, autopct='%1.1f%%', startangle=140)
ax2.set_title('World Population Share by Continent (2022)')

# Plot 3 — Population trend (world total per decade)
ax3 = axes[1, 0]
years = [1970, 1980, 1990, 2000, 2010, 2015, 2020, 2022]
cols  = ['1970 Population','1980 Population','1990 Population','2000 Population',
         '2010 Population','2015 Population','2020 Population','2022 Population']
world_totals = [df[c].sum() / 1e9 for c in cols]
ax3.plot(years, world_totals, marker='o', color='darkorange', linewidth=2, markersize=6)
ax3.fill_between(years, world_totals, alpha=0.15, color='darkorange')
ax3.set_xlabel('Year')
ax3.set_ylabel('Population (Billions)')
ax3.set_title('World Total Population Growth (1970–2022)')
ax3.grid(alpha=0.3)

# Plot 4 — Average density by continent (bar)
ax4 = axes[1, 1]
density_sorted = density.sort_values(ascending=False)
ax4.bar(density_sorted.index, density_sorted.values, color='mediumseagreen')
ax4.set_xlabel('Continent')
ax4.set_ylabel('Avg Density (per km²)')
ax4.set_title('Average Population Density by Continent')
ax4.tick_params(axis='x', rotation=20)
ax4.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig('world_population_analysis.png', dpi=150, bbox_inches='tight')
plt.show()
print('Chart saved!')

"""---
## 8. Summary & Key Findings
"""

print('=' * 55)
print('         WEEK 1 — KEY FINDINGS SUMMARY')
print('=' * 55)
print(f'  Dataset size        : {df.shape[0]} countries × {df.shape[1]} columns')
print(f'  Missing values      : {df.isnull().sum().sum()}')
print(f'  Duplicate rows      : {df.duplicated().sum()}')
print(f'  Continents covered  : {df["Continent"].nunique()}')
print(f'  World pop (2022)    : {df["2022 Population"].sum()/1e9:.2f} Billion')
print(f'  Most populous       : {df.loc[df["2022 Population"].idxmax(), "Country/Territory"]}')
print(f'  Least populous      : {df.loc[df["2022 Population"].idxmin(), "Country/Territory"]}')
print(f'  Fastest growing     : {df.loc[df["Growth_%"].idxmax(), "Country/Territory"]} ({df["Growth_%"].max():.1f}%)')
print(f'  Highest density     : {df.loc[df["Density (per km²)"].idxmax(), "Country/Territory"]}')
print('=' * 55)